#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := 04-button

EXTRA_CFLAGS += -I../.. -DHOMEKIT_SHORT_APPLE_UUIDS

EXTRA_COMPONENT_DIRS += ../../components/
EXTRA_COMPONENT_DIRS += ../../components/general

include $(IDF_PATH)/make/project.mk


